### ISSUE TITLE
Simplified example app

### ISSUE THREAD

**Issue by bartolkaruza** [bdefore/redux-universal-renderer#1]
Hi, started trying to get a minimal example running, instead of the example provided. I'm having trouble getting it to work properly following just the instructions of the README. Any chance someone could help out? 

[the project](https://github.com/bartolkaruza/universal-redux-simple-example)

**Comment by bdefore** [comment]
Thanks @bartolkaruza. I've submitted a PR for you: https://github.com/bartolkaruza/universal-redux-simple-example/pull/1

In the meantime, based on what came out of that, I've opened the following issues #3 #4 #5
