### ISSUE TITLE
requirements for 2.x

### ISSUE THREAD

**Issue by bdefore** [bdefore/redux-universal-renderer#10]
I'd like to open this up to debate in case there are ideas on what should be included in the package for the next versions. Current thoughts on what version 2.x will define as peer dependencies:
- Babel 6 (and its set of loaders, plugins, transforms)

**Comment by bdefore** [comment]
Some exploring of Babel 6 now happening on `babel6` branch https://github.com/bdefore/universal-redux/tree/babel6

**Comment by lndb** [comment]
Some ideas:
- Moving from Express to the next generation web framework [koa](http://koajs.com/), especially the newest [2.x branch](https://github.com/koajs/koa/tree/v2.x).
- [Inline Styles](https://github.com/erikras/react-redux-universal-hot-example/blob/master/docs/InlineStyles.md): [Radium](https://github.com/FormidableLabs/radium) looks interesting.

**Comment by bdefore** [comment]
thanks @indb for the suggestions! i have had a few others ask for koa support. i think the ideal implementation would be something that universal-redux would allow for either a koa or express instance to be passed to it. i'm unfamiliar with koa, though, so perhaps you could suggest: would it be trivial to modify this area to be both koa and express compatible? https://github.com/bdefore/universal-redux/blob/master/src/server.js#L72-L128

**Comment by bdefore** [comment]
2.0.0 has now dropped and dependencies locked in. I'm going to close this, please contribute further suggestions to #25
