### ISSUE TITLE
Best way to setup source locally?

### ISSUE THREAD

**Issue by adailey14** [bdefore/redux-universal-renderer#11]
@bdefore This is more a general npm question, maybe you wouldn't mind answering: What is the best way to setup the universal-redux source alongside an example project so you can change the universal-redux code and see it in action in the example project? (My purpose being to dig into the hot reloading issue)

I've tried:

```
cd my_example_directory
npm install ../../my_local_directory/universal-redux
```

That kindof seems to work but has to fight through some errors, and doesn't really feel right. Could you share how you have this setup? Sorry if this is some basic stuff, I'm new to 'advanced' npm usage.

**Comment by bdefore** [comment]
@adailey14 I've been meaning to explore `npm link` more to see if it is preferable, but for now I've been following these steps: https://github.com/bdefore/universal-redux#local-development

**Comment by bdefore** [comment]
Also, the hot reloading issue appears to occur even in the latest of the react-redux-universal-hot-example project, at least for me, so I'm beginning to think it's not anything related to universal-redux.

**Comment by adailey14** [comment]
Wow can't believe I missed that in the readme. I think it's going to take me a few days of tinkering around with this before I can contribute anything useful but I'll try to keep at it.
