### ISSUE TITLE
Question about waiting for Server Requests

### ISSUE THREAD

**Issue by davidfloegel** [bdefore/redux-universal-renderer#110]
Hello,

I'm playing around with the starter kit at the moment and so far I like it.

One thing I have to achieve is this:
Fetching data (for example a profile) from the server, putting some data (i.e. name, location, image) into the meta tags and then render the page so for example Facebook can display the preview.

So far I tried a simple fetch on componentDidMount but obviously I'll have to display a loader of some sorts until the request is successful. In this time, facebook will have already crawled the page and won't find any data.

Do you have any suggestion on how to tackle that? My apologies if this has been asked before, but I can't really find a response

Thanks a lot!

David

**Comment by bdefore** [comment]
Hi David. What you speak of is partially supported using fmp-redux-async-connect (https://github.com/findmypast/redux-async-connect), but that library appears to not be updated anymore. At the moment, I'm not familiar with a replacement that works with UR. Here is an example of another that could be adapted to work: https://github.com/ericclemmons/react-resolver
