### ISSUE TITLE
fetchAllData sometimes gets into loop

### ISSUE THREAD

**Issue by bdefore** [bdefore/redux-universal-renderer#16]
It has been removed for 2.0.0-beta5 pending resolution of https://github.com/jlongster/react-redux-universal-hot-example/pull/4

**Comment by bdefore** [comment]
Exploring react-fetcher as an alternative on a branch. But it will also need to change when the new React Router API drops: https://github.com/erikras/react-redux-universal-hot-example/pull/531

**Comment by tadeuszwojcik** [comment]
Hi, I've spent way to much time choosing starting point for new project and finally settled on your project. Great work!
Is there a chance you'll bring back fetchData, or alternative way of fetching data for server-side rendering in near future? Or perhaps it's outside of scope of that project?
Cheers

**Comment by bdefore** [comment]
@tadeuszwojcik definitely near future. a hook for serverside fetching is a core piece of what universal-redux should provide, and ideally it should also allow custom serverside render hooks in case you want to do roll your own fetching logic (a kind of 'universal rendering middleware'). work on this has been blocked by the changes in updating to react-router 2.0, which are now nearly stable in the 3.x version of UR, and it's there that i intend to look into plugging in either react-fetcher or something like it. whether that makes it back to 2.x depends on if redux-simple-router can support it, which depends on the issue above. at this point i'd recommend going with UR 3.x unless there's an issue with your project code an react-router 2.0-rc4.

**Comment by bdefore** [comment]
I'd like to keep this issue open for mainly for backward compatibility, about returning fetchData to 2.x, and #43 for about new and potentially different ways of solving the same problem.

**Comment by tadeuszwojcik** [comment]
cool,  thanks for the update!

**Comment by bdefore** [comment]
@tadeuszwojcik Release 3.0.0-rc5 has async-props support. Put a static loadProps function on your views to use. https://github.com/rackt/async-props#usage

**Comment by bdefore** [comment]
3.0.0-rc16 now uses redux-async-connect. More info here https://github.com/bdefore/universal-redux/issues/50#issuecomment-173091675

**Comment by shilpan** [comment]
How do you recommend using it with: http://erikras.github.io/redux-form/#/api/reduxForm?_k=ercae5

**Comment by bdefore** [comment]
@shilpan you should be able to use both the `@asyncConnect` and `@reduxForm` decorators on your components.
