### ISSUE TITLE
Babel warnings

### ISSUE THREAD

**Issue by dts** [bdefore/redux-universal-renderer#17]
I started up a fresh copy with the most recent NPM beta, thinking I was following the instructions, but I got some warnings about babel not being installed and then babel-cli being what actually needs to be installed.  I haven't gotten much further, I just wanted to take keep a note of installation confusion that happened, so we can either streamline the installation/startup process or by amending the documentation to match the process.

**Comment by bdefore** [comment]
@dts do you have babel 5 installed globally? i do need to add that to the instructions to uninstall it if you do. also, how do your dependencies compare to the minimal example? https://github.com/bartolkaruza/universal-redux-simple-example/blob/master/package.json

**Comment by dts** [comment]
Not sure about babel 5, as I have not clobbered whatever state I had to begin with.  I started with the simple example you listed (just git pull'ed it into an empty repo), and had to add these dependencies in order to get it to start up and work as I expected:

```
    "babel-eslint": "^4.1.6",
    "babel-plugin-react-transform": "^2.0.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-runtime": "^6.3.13",
    "babel-plugin-typecheck": "^3.5.1",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babel-preset-stage-0": "^6.3.13",
    "babel-runtime": "^6.3.19",
    "redux-simple-router": "1.0.1",
```

 Ideally these would live inside the universal-redux dependency, right?  Requiring a bunch of peer dependencies seems like it defeats part of the point of this repo.

**Comment by bdefore** [comment]
@dts are you installing dependencies with npm 2?

**Comment by dts** [comment]
Argh, shite - ya got me.  Somehow I was using npm 2.  I still haven't figured out `n` and node/npm version management.  Thanks.

**Comment by dts** [comment]
I'm gonna close this, haven't had this issue with npm 3, thanks!
