### ISSUE TITLE
Reducers API

### ISSUE THREAD

**Issue by dts** [bdefore/redux-universal-renderer#19]
Many of the older examples demonstrates combining reducers with combineReducers in the `redux/modules/index.js` file (https://github.com/bdefore/universal-redux/tree/0.x/examples/jwt), but in https://github.com/bdefore/universal-redux/blob/master/src/redux/create.js#L28, it demonstrates that the correct way to specify them is to export a hash that will be extended and fed into combineReducers, like so:

```
import signupReducer from './signup/index';

export default {
  signup: signupReducer,
};
```

It's an important enough difference from "redux standard" that I think it should merit a mention in the main README until a larger documentation base is ready.

**Comment by bdefore** [comment]
@dts this changed in the beta drops of 2.0, as i felt like it streamlined the process that users didn't need to know about redux-simple-router needing to be defined here, that the universal-redux library could handle it for you. how do you feel about it? i'm not entirely satisfied with it, and have been exploring other ways and may retract it before the official 2.0.

**Comment by dts** [comment]
The ideal case, IMHO, is unfortunately the hardest one: do not require the redux-simple-router call, but allow the user to supply a normal Redux reducer function, as it maintains the API simplicity that makes redux so wonderful.  Internally, it would look like this:

```
function universalReduxRootReducer(state,action) {
  state = { state... , _routing: routerReducer(state._routing,action) };
  state = userReducer(state,action);
}
```

**Comment by bdefore** [comment]
@dts what you're desiring is a bit of a wrapper around the redux simple router, which i think i'd prefer to let the project developer decide how best to do. in which case, the newer API is too proscriptive, and I think it's best to return to a place where it's up to you how you and where you'd like to manage `routeReducer`.

**Comment by bdefore** [comment]
2.0.0-beta13 returns to the previous behavior, expecting user to return a `combineReducers` object with redux-simple-router's routeReducer as one of them. An example: https://github.com/bdefore/universal-redux/blob/master/examples/jwt/src/redux/modules/index.js
