### ISSUE TITLE
Separate devDependencies

### ISSUE THREAD

**Issue by chrisblossom** [bdefore/redux-universal-renderer#2]
Most of the dependencies in [package.json](https://github.com/bdefore/universal-redux/blob/master/package.json#L34) are for development. What do you think about splitting out the devDependencies into another repository?

Usage instructions would be something like:

```
npm --save universal-redux
npm --save-dev universal-redux-dev
```

**Comment by bdefore** [comment]
@chrisblossom I'm not familiar with that approach. I'd be concerned about separating tests out from the main repo. If you'd like to reduce your `npm install` time, `devDependencies` are not installed with the `npm install --production` flag.

**Comment by chrisblossom** [comment]
@bdefore maybe I am just confused how to use this package, but currently if I deploy an app with universal-redux as a dependency, it will also npm all production dependencies listed inside universal-redux as well. In reality, the majority of these are devDependencies.

The only way I can see to separate production and dev dependencies is to have two separate npm packages.

Does that make sense?

**Comment by bdefore** [comment]
@chrisblossom i can see your point. i'll have a look into how to configure them differently.

**Comment by bdefore** [comment]
@chrisblossom i'd like to understand your deploy setup. pulling the deploy bits out of this repo might end up being the best path, at which point many of them could move to being devDependencies. can you hit me up on reactiflux?
