### ISSUE TITLE
Production deployment guide?

### ISSUE THREAD

**Issue by dts** [bdefore/redux-universal-renderer#21]
I am a bit confused on the production side of this package - I ran:

```
NODE_ENV=production npm run build
NODE_ENV=production node_modules/.bin/universal-redux-server
```

When I build using the wrong NODE_ENV, the ports get mixed up for the resources, but this one appears to be correct.  When I do this I get 500 errors from the server with no logging on the terminal, and no errors reported in the HTTP response (past the 500 error code).  I have been trying to add error handlers in the universal-redux repo (using the local dev instructions), but have not turned anything up yet.

**Comment by dts** [comment]
Figured it out - I had left out the static serving directory from the config.  The reason no errors were being logged is these lines, which do not log meaningfully: https://github.com/bdefore/universal-redux/blob/dbc256defe6f9a32cb04970704d06ed5065f5419/src/server.js#L99-L101.  Printing an error here would have helped a bit.  Also, a warning message that there is no static directory specified, or having a default value would have made this easier to identify.

**Comment by bdefore** [comment]
Ah, interesting. The static asset serving is now optional, and should not have errorred out that way. I'll look into this.

**Comment by bdefore** [comment]
Do you mean you had not configured a `staticPath`? Were you then getting 500 errors for requests in your static directory?

**Comment by dts** [comment]
What happened to me is I clobbered the static asset serving setting to false, which means that every request was being served by the react router - and I hadn't added a 404 route to that router, so I was getting to the lines above, (renderProps was null), so it was just rendering a 500 over the wire and not erroring anywhere else.

**Comment by bdefore** [comment]
OK. Would very much welcome PR's around better error handling, with some steps for reproducing. :+1:

**Comment by dts** [comment]
Perfect - I don't think reproduction on your side is really a necessity - I'll put together a PR and send it in a bit.

**Comment by dts** [comment]
PR submitted: https://github.com/bdefore/universal-redux/pull/23.  Closing.

**Comment by bdefore** [comment]
Reopening as the larger issue is that `staticPath` was not actually allowed as optional, with a fallback to the default.

**Comment by bdefore** [comment]
There is now no longer a default, which was making guesses about project root. `staticPath` defined in project configuration is required in order to serve Express assets.
