### ISSUE TITLE
Webpack 2

### ISSUE THREAD

**Issue by bdefore** [bdefore/redux-universal-renderer#22]
Particularly interested in the new tree-shaking options, outlined here:

http://www.2ality.com/2015/12/webpack-tree-shaking.html
https://medium.com/@matt.krick/a-production-ready-realtime-saas-with-webpack-7b11ba2fa5b0#.pejilqpg6

A little early to migrate though?

**Comment by dts** [comment]
You're talking about migrating to WP2?  Meh, I think that once UR2.0 is ready for the big-time, so will webpack 2.  We're on the bleeding edge as it is, and tree shaking and the automatic splitting (sweet feature of meatier) would be huge.  Any reason we don't try to merge meatier and UR?  He appears to be on a slightly different track, but the foundations are the same - can you see some reason why they should be completely separate?  I'd rather get away from the "let's just make another tool!" attitude that is prevalent in the Node community...

**Comment by bdefore** [comment]
Yeah, this is definitely intended for later. Mostly just would like to get a discussion going or open it up for anyone else to contribute if they wish.

I like a lot of the goals and tech choices of Meatier. It's much more proscriptive though: MongoDB integration, token auth (on localStorage??), and a lot of proscription around sockets.

**Comment by dts** [comment]
I don't want any DB integration baked-in - I like the way UR allows you to separate the API completely.  I understand Rails' security concerns better than Node's, so I'm going to keep that stuff in rails for a while.  I am more thinking about building out a plugin architecture and ecosystem around UR that allows hooking reasonably into the stack, so you could add a lot of these things at a plugin level.  A lot of people do token auth in localStorage - the API is way better than cookies out of the box, though there are libraries that store tokens in cookies better these days.

**Comment by bdefore** [comment]
As far as I'm aware, cookie storage via `httpOnly` offers an additional security over local storage, which could be accessed by third-party JavaScript that you bundle into your app. https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage/

**Comment by dts** [comment]
Sold!  Cookies + XSRF tokens are probably the best combo.  Still, this doesn't belong in the basic framework IMHO, but a few different models would make sense to add in plugin form.
