### ISSUE TITLE
suggestions for 3.x

### ISSUE THREAD

**Issue by bdefore** [bdefore/redux-universal-renderer#25]
@indb has suggested looking at:
- koa
- Radium (inline styles)

I'm not sure if Radium will make it for this release, but in regards to Koa, I am interested in exploring the following plan for supporting it:
- allow universal.app() to accept an instance of Koa (as it currently does with an Express instance)
- breaks off serverside rendering into a new library which universal-redux-server will use
- internal to universal-redux-server, detect Express or Koa and do what's expected based on what's returned from this new library

Thoughts?

**Comment by catamphetamine** [comment]
If you have questions about koa you can ask them here.
Koa is similar to express, but express middleware doesn't work for koa.
The idea is the same though, the only difference are generators instead of normal functions.

**Comment by lndb** [comment]
Async/await instead of generators if using Koa 2.x

Using [react-helmet](https://github.com/nfl/react-helmet) instead of react-document-meta.

**Comment by dts** [comment]
I am somewhat familiar with Koa, and the syntax is cool, and lets you do neat things with middleware that were annoying with Express.  Are there specific use cases that make it a high priority?

**Comment by arkist** [comment]
inline-styles still has many problems. if using it with external style, it's too hard to manage. and have no emmet supported yet. css-modules is fine enough.

**Comment by bdefore** [comment]
@arkist i agree. i think given the churn in css with react it will be best to leave things with css modules for now, but allow people to configure webpack to use whatever other setups they need. radium should be possible without it being built in.

**Comment by catamphetamine** [comment]
@arkist what "many problems" do inline styles have?

**Comment by arkist** [comment]
@halt-hammerzeit as I mentioned,
1. It is hard to manage. Imagine if you using CSS framework like bootstrap. Still keep in mind how whole external styles and override CSS props. not all the styles in inlined, adding some styles in 'inline' can't save us.
2. All the pseudo selectors/elements. writing more `'` is feel so annoying. and can't handle pseudo element correct way.
3. No Emmet/IDE support. typing is very tired. and people miss types usually.
4. Not the Standard. most of 'inline-styles' using camelCase and 'string' and can not be supported CSS' good parts. 

if you make every part from scratch or using inline-styled-react-components-only, inline styles may help you. but if not, can not recommend IMHO.

**Comment by catamphetamine** [comment]
The only things I can agree are no pseudo elements and no pseudo selectors, no IDE support, no autocompletion.

I don't agree with your other statements.

External styles are more feature-rich, and that's the only thing about them.

**Comment by bdefore** [comment]
In case anyone is interested in koa support, I've done some work to pull out the serverside rendering into an Express middleware, that's ripe for someone making a koa version. #38

**Comment by bdefore** [comment]
Koa support is now merged in with #60 and released with 3.0.1
