### ISSUE TITLE
Seems server works without webpack, so no hot reloading on server?

### ISSUE THREAD

**Issue by olegmalkovdev** [bdefore/redux-universal-renderer#28]
Seems server works without webpack, so no hot reloading on server?
Is it hard to implement it? Like here https://github.com/jlongster/backend-with-webpack

**Comment by dts** [comment]
Production does not use the webpack dev server, but the development mode does - it is just hidden inside the universal-redux package, so you don't have to interface with it directly if you don't want to.

**Comment by olegmalkovdev** [comment]
I need hot reloading on server in development mode. I am trying to load markdown files via webpack loader(https://github.com/coderany/markdown-with-front-matter-loader)

It gives me hot reloading of my markdown files so i can instantly see the changes in browser
But right now webpack is using only on dev server on port 3001 that serving js bundle for browser only
And after page reloading i have different generated html on server and on client because server works without hot reloading

**Comment by bdefore** [comment]
@coderany hot reloading should be working in development. how are you configuring your markdown loader with universal redux? can you post your universal-redux-config.js ?

**Comment by olegmalkovdev** [comment]
The problem was on server side (port 3000), i fix my errors by adding webpack-isomorphic-tools-config.js with parser for *.md

Thx
