### ISSUE TITLE
Error: Cannot find module "middleware"

### ISSUE THREAD

**Issue by dts** [bdefore/redux-universal-renderer#30]
Just upgraded to v2.0.0 (from beta 12 or something), and I got this error:

`Module parse failed: <app>/node_modules/universal-redux/src/redux/middleware/index.js Line 2: Unexpected token`

I don't actually see what the unexpected token is, this is the code I have:

```// user provided redux middleware
export default {};

``````

And this is what it compiled to:

```"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
// user provided redux middleware
exports.default = {};```
``````

**Comment by bdefore** [comment]
@dts i've never seen this error. can you update to 2.1.1 and try again? What kind of middleware are you using in your app?

**Comment by dts** [comment]
I am not using any, but upgrading to 3.0.0 and wipe-reinstall-wiping a few times made it go away.  Sigh.

**Comment by bdefore** [comment]
@dts the 3.0.0 betas are going to be a little more cutting edge as it relies on an unfinished react-router integration. i'd recommend you stay with 2.x for now unless you really want to update to their new API. the error you were getting on middleware should not be happening, particularly after some cleanup i've done as of the 2.2.1 release. i'd be curious if you saw the same issue after dropping back down, blew away your node_modules and tried again.
