### ISSUE TITLE
Hydrate redux store with immutable data.

### ISSUE THREAD

**Issue by cwbutler** [bdefore/redux-universal-renderer#31]
I want to supply my redux store's initial data as an Immutable. I see I can override the HtmlShell.js and use 'transit-immutable-js' to send the data correctly, but the client doesn't support hydrating the store with immutable objects.

Could it be possible to check to see if the initial data is immutable, and if so use 'transit-immutable-js' to convert?

**Comment by bdefore** [comment]
@cwbutler i'd like to know more about the hangups regarding immutable and what the client is doing. best ping me on discord reactiflux #react-redux-universal i'm @buck over there.

**Comment by cwbutler** [comment]
Ok will do, 

Just to sum up... my problem deals with this line of code.
`const store = createStore(reduxReactRouter, makeRouteHooksSafe(getRoutes), scrollableHistory, client, window.__data);`

My react application assumes that the state is an Immutable state object, but with that line of code in client.js I can not make this assumption. 

I would like `windows.__data` to be an immutable data structure. 

I know I can override HtmlShell to send the data as a serialized immutable object like so... 
`import { toJSON } from 'transit-immutable-js';`
`const data = toJSON(store.getState());`
`...`
`<script dangerouslySetInnerHTML={{__html:`window.__data=${data};`}} charSet="UTF-8"/>`
but client.js will always try to initialize the store with a native JS object.

The solution I propose is to incorporate 'transit-immutable-js' into client.js

`import { toJSON, fromJSON } from 'transit-immutable-js';`
`...`
`const data = fromJSON(toJSON(window.__data));`
`const store = createStore(middleware, browserHistory, reducers, data);`

The goal is to seamlessly send initial state data from server to client. 
If the data is a native object or ImmutableJS object, it will be converted to string form by toJSON, then it will be converted either back to it's native form, or to immutable object.

**Comment by cwbutler** [comment]
Ah! Answered my own question.

Inside my custom HtmlShell, I converted the data with 'transit-immutable-js' inside the script tag.
`import { toJSON, fromJSON } from 'transit-immutable-js';`
`const data = toJSON(store.getState());`
`...`
`<script dangerouslySetInnerHTML={{__html:window.__data=${fromJSON(data)};}} charSet="UTF-8"/>`

**Comment by cwbutler** [comment]
Just for document purposes, I **did away with transit-immutable-js** as it was a heavy dependency and plain js could solve my problem.

I converted the initial state to an immutable object if it the state is passed in as a mutable object. 
I accomplished this with the help of [redux-immutablejs](https://github.com/indexiatech/redux-immutablejs). I combine my reducers the normal way with **redux**'s combineReducers, but I create my individual reducers with **redux-immutablejs**'s [createReducer](https://github.com/indexiatech/redux-immutablejs#immutable-handler-map-reducer-creator). 

This essentially does the conversion for me and I can now accept native objects in my app, but assume immutable.

Thanks @bdefore for this module. Thanks @dts for leading me in this direction.

**Comment by cchamberlain** [comment]
@cwbutler I just wrote [fire-hydrant](https://github.com/cchamberlain/fire-hydrant) (similar to transit-immutable-js) to fix my issue of having immutables in random spots in my state tree. It is very light on dependencies:

![image](https://cloud.githubusercontent.com/assets/424694/15343268/30a612f4-1c50-11e6-89b8-684eec0e1452.png)

```
import { serialize, fromHydrant } from 'fire-hydrant'


/** server side rendering to script */
<script dangerouslySetInnerHTML={{ __html: `window.__initialState__ = ${serialize(store.getState())}` }} />

/** client recursive hydration, restore regular object with optional immutables at top or subtree levels */
let initialState = fromHydrant(window.__initialState__)
```

Posting in case anyone is still having issues with this.
