### ISSUE TITLE
Annotated universal-redux.config.js example is a function

### ISSUE THREAD

**Issue by philiplopez** [bdefore/redux-universal-renderer#36]
Found in version 3.0.0-beta6.

As per README.md, the [annotated example](https://github.com/bdefore/universal-redux/blob/master/config/universal-redux.config.js) should be used as a starting point. That defines config as a function `(projectRoot, sourceRoot) => config`.

However, based on the behaviour in [src/server](https://github.com/bdefore/universal-redux/blob/master/src/server.js), the custom config should simply be an object, as in the JWT proxy example [config file](https://github.com/bdefore/universal-redux/blob/master/examples/jwt/config/universal-redux.config.js).

Options as I see it:
1. Change the behaviour of server.js to invoke the config as a function (like the default config is); or
2. Change the annotated config (which is actually the one used by server.js); or
3. Make the documentation very clear as to the alternative.

I would recommend Option 1 so that the projectRoot and sourceRoot don't have to be determined again (and perhaps differently) - unless that's a desirable feature.

p.s. Apart from this hassle, I really like the approach taken in universal-redux to avoid copying lots of (easily-out-of-date) boilerplate, so thanks!

**Comment by bdefore** [comment]
@philiplopez That's an excellent idea. The documentation drifted a little bit here since the config file was made optional. Option 1 sounds good to me. A PR for that would be very welcome :beer: !

**Comment by bdefore** [comment]
@philiplopez For the goal of simplifying getting started, as of 3.0.0-rc27 the project root is now fixed to `process.cwd()` and `src` is the required source root. This removed the need to pass these properties to UR and means you'll again be able to copy the annotated universal-redux.config.js directly into your project.
