### ISSUE TITLE
Serverside rendered styles in development

### ISSUE THREAD

**Issue by bdefore** [bdefore/redux-universal-renderer#37]
Although in production we rely on ExtractTextPlugin for access to styles, they are not available in dev without an uncomfortable workaround of adding them explicitly to a custom HtmlShell. It'd be nice if they were automatically brought in for dev the same way they are in production.

Possible option: BrowserSync and ExtractTextPlugin, a la https://github.com/erikras/react-redux-universal-hot-example/pull/693

@chrisblossom I'd love to see an analogous PR if you could whip something up.

**Comment by dts** [comment]
Is server-side rendering even an issue in development?  Why would it be important?

**Comment by bdefore** [comment]
There's a few things that would be nice:
- Less time waiting after an `npm run dev` starting up and being able to see a fully styled page render
- Parity between the developer's visual experience and the experience on production, without FOUC.
- Parity between deploys and the developer's setup, if the ExtractTextPlugin is configured the same on both. This means one less piece to consider behaving differently at deploy time.
- Removing what I see as some technical debt / fanciness around webpack-isomorphic-tools providing serverside style rendering.

**Comment by dts** [comment]
All good points, though I would argue that this is a relatively low priority, compared with server-side resource fetching, for example.
