### ISSUE TITLE
Error adding middleware

### ISSUE THREAD

**Issue by shilpan** [bdefore/redux-universal-renderer#42]
I am trying to add a middleware like so in `middleware/index`:

``` javascript
function thunkMiddleware({ dispatch, getState }) {
  return next => action =>
    typeof action === 'function' ?
      action(dispatch, getState) :
      next(action);
}

export default {
  thunk: thunkMiddleware
};
```

And my action is as such:

``` javascript
export const ingredientsQuery = ({field}) => {
  return dispatch => {
    dispatch(requestFetch(field));

    return new Promise((resolve) => {
      setTimeout(() => {
        resolve([
          'Water',
          'Milk',
          'Curd'
        ]);
      }, 100); // simulate server latency
    }).then(data =>
      (dispatch(requestRecieve(data, field))));
  };
};
```

I keep getting the error:

```
Warning: Failed propType: Invalid prop `action` of type `function` supplied to `LogMonitorEntry`, expected `object`. Check the render method of `LogMonitor`.
```

And none of my actions inside the thunk function are being dispatched. It seems like `thunk` the middleware is not getting attached. Or is there something I am doing wrong?

**Comment by bdefore** [comment]
@shilpan are you using 2.x or 3.x?

**Comment by shilpan** [comment]
@bdefore 2.x

**Comment by shilpan** [comment]
@bdefore just upgraded to 3.x and I seem to still have the same problem

**Comment by bdefore** [comment]
@shilpan i'm trying to reproduce what you're describing but `requestFetch` and `requestReceive` are not defined. can you look at the `thunk-middleware` branch of the starter project here: https://github.com/bdefore/universal-redux-starter/tree/thunk-middleware?

also with version 3.0.0-rc3 I've modified how redux middleware are processed. you might want to follow #38 as well.
