### ISSUE TITLE
How to prefetch data into redux store using asyncProps? 

### ISSUE THREAD

**Issue by sergesemashko** [bdefore/redux-universal-renderer#50]
Hi,

I'm trying to prefetch data on server and pass it to client in redux store, but can't figure out how. I've noticed asyncProps were applied and replaced fetchData methods. 

Is there any example how to do it? 

Also, [this issue](https://github.com/rackt/react-router/issues/1623) might be relevant, even if it's old. Async-props maps loaded data to properties, seems like the same can be done by redux [connect](https://github.com/rackt/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options), if I'm not mistaken. 

This is the code I ended up with, but with no result:

``` js
@connect(
  state => ({
    data: state.data
  }),
  {...dataListActions})
class App {
  static loadProps(params, cb) {
    console.log(this.props); // undefined
    let {dispatch} = this.props; // error
    loadData().then(response => {
      dispatch(actionCreator({response, type: 'success'}));
      /* should we call cb() if redux store is already updated and data is 
      mapped to props? calling async-props callback here will override existing props */
      cb(null, response); 
    })
  }
}
```

Thanks in advance

**Comment by sars** [comment]
Hi! I use https://github.com/Rezonans/redux-async-connect for this reason
It's difficult to understand what's the problem without seen your reducer
You use loadProps correctly. Regarding callback - you can just call it with null result: 
cb(null)
In your case it only needed to say Async Props, that data have already been fetched.
Regarding dispatch function. You can use in from store in context:

 this.context.store.dispatch

**Comment by YAndrew91** [comment]
@sars, `loadProps` is a static method, you can't access context there.
@sergesemashko, you can make a link to your store be passed into `params` of the `loadProps` and then unpack `dispatch` and `getState` methods from it, see an [example of appr changes in universal-redux](https://github.com/YAndrew91/universal-redux/commit/394598ffc72c9e9cc2ccaccfbc588005e71c62dd).

**Comment by sars** [comment]
@YAndrew91 Oh, yes.. you are right...
Actually I made the same when I used AsyncProps, but it's bad practice to mutate params object,
please, see https://github.com/rackt/async-props/issues/43

There is special helpers in redux-async-connect for such purposes, that you can pass:
https://github.com/sars/appetini-front/blob/appetini/src/client.js#L22

store is passed automatically 
https://github.com/sars/appetini-front/blob/appetini/src/containers/App/App.js#L22

**Comment by bdefore** [comment]
I'm getting a little wary of async props after discovering this this morning: https://github.com/rackt/async-props/issues/50

I've got a PR open experimenting with redux-async-connect as a replacement: https://github.com/rackt/async-props/issues/50

Open to feedback, and if you can review those changes @sars I'd be much obliged.

Also, this is making me feel like having a `providerWrapper` (so people can choose their own serverside fetching library) is going to be important sooner rather than later https://github.com/bdefore/universal-redux/issues/48

**Comment by bdefore** [comment]
Upon further deliberation, async-props has not been a great fit so far:
- its callback nature doesn't map well to redux connect
- its creators consider it experimental and does not seem to be getting active development
- a rather significant bug that breaks routes with dynamic segments (i.e. /users/:id)
- it's more complex than it needs to be

For these reasons, I've decided to take it out of UR for the time being, in lieu of @sars redux-async-connect, starting with 3.0.0-rc15. It feels much closer to the Redux ideal than async-props or the fetchData approach used in RRUHE.

Apologies @YAndrew91: I expect that might affect you. With some work on #48, we should be able to get to a point where serverside fetching and redux route helpers can be configurable.
