### ISSUE TITLE
Migration to Redux Async Connect

### ISSUE THREAD

**Issue by sars** [bdefore/redux-universal-renderer#51]
Hi there
This lib should fit universal-redux much better: 
It's integrated with redux and react router, and avoid a lot of routine tasks to save fetched data to store.
I think it should be much more convenient than Async Props, because it stores data to redux state. 
https://github.com/Rezonans/redux-async-connect

**Comment by sars** [comment]
Related to https://github.com/bdefore/universal-redux/issues/50

**Comment by bdefore** [comment]
Agreed. Finished in #52 and released as 3.0.0-rc16
