### ISSUE TITLE
Enable ability to replace configs entirely

### ISSUE THREAD

**Issue by XiXora** [bdefore/redux-universal-renderer#66]
Currently, I am having trouble with loaders specifically as I have component folders use CSS modules and others do not.
The way that they merge at the moment doesn't allow a user to replace certain tests, only add to an array.

The way I see it is if you have webpack.config.js in the same folder as your universal-redux.config.js, use that as your base config.
However, there are a few configuration values (babel-loader) in merge-configs.js that get added after merging that may need to removed or moved elsewhere.
Perhaps there is a better way?

**Comment by bdefore** [comment]
@XiXora i'd like to understand your use case a little better to see if this could be solved via an API. i sounds like you'd like to override the defaults for webpack loaders, potentially to add an 'exclude' directory? could you tell me more about how you're structuring your division between component styles and general ones?

are there babel configurations in the default that you want to opt out of?

**Comment by XiXora** [comment]
Currently, I have commented out the less (and scss) loaders from u-r and have added my own less loaders in my config.

Less loader that looks in my components folder are CSS module based
Less loader that excludes my components folder is not module based
CSS loader that includes autoprefixer (aside, has this been updated to postcss now?).
JS loader that only includes my source root.

**Comment by bdefore** [comment]
Related #83
