### ISSUE TITLE
Cleaning the dist folder

### ISSUE THREAD

**Issue by jaydenseric** [bdefore/redux-universal-renderer#69]
The `static/dist` folder never seems to get cleaned, after several hours of dev it get really full with redundant files. That directory could get out of hand pretty quick if you work with a lot of media assets.

What is the recommended approach to cleaning? I stop everything, delete `static/dist`, run a build and restart dev.

**Comment by bdefore** [comment]
@jaydenseric are you running `npm run build` during development? if you are running `npm run dev` you shouldn't see anything created in static/dist.

**Comment by jaydenseric** [comment]
Ahh, I assumed to get started you have to run `npm run build` before `npm run dev`. [universal-redux-starter](https://github.com/bdefore/universal-redux-starter) doesn't have a readme yet, but if it ever does it would be nice to have a simple explanation of how to use the npm scripts.

Would it be a nice enhancement for the build script to clean out the previous build first anyway? Running consecutive builds is how you would regularly update a production site?

**Comment by bdefore** [comment]
@jaydenseric There is this plugin, if you'd like to pursue it: https://github.com/johnagan/clean-webpack-plugin
