### ISSUE TITLE
redux modules sometimes do not hot reload

### ISSUE THREAD

**Issue by bdefore** [bdefore/redux-universal-renderer#7]
Currently, reducers are not hot reloading. You'll see the following console error when you change one:

```
[HMR] The following modules couldn't be hot updated: (Full reload needed)
[HMR] - ./src/redux/modules/auth.js
```

I'm not certain why this is the case. The [base example project](https://github.com/erikras/react-redux-universal-hot-example) that this library is derived from works fine. Its serverOptions are unchanged (publicPath also resolves to the same):

```
var serverOptions = {
  contentBase: 'http://' + host + ':' + port,
  quiet: true,
  noInfo: true,
  hot: true,
  inline: true,
  lazy: false,
  publicPath: webpackConfig.output.publicPath,
  headers: {'Access-Control-Allow-Origin': '*'},
  stats: {colors: true}
};

var app = new Express();

app.use(require('webpack-dev-middleware')(compiler, serverOptions));
app.use(require('webpack-hot-middleware')(compiler));
```

It assigns the following lines in `src/redux/create.js` for hot reloading: 

```
module.hot.accept('./modules/index', () => {
  store.replaceReducer(require('./modules/index'));
});
```

An example of this reducer index:

```
import { combineReducers } from 'redux';
import auth from './auth';
import { routerStateReducer } from 'redux-router';

export default combineReducers({
  auth,
  router: routerStateReducer
});
```

`universal-redux` allows the reducer index path to be configurable, which means I tried to modify it to the following, with an example of `__REDUCER_INDEX__` being an absolute path like the following: `/Users/d4/code/my-project/src/redux/modules/index.js`

```
module.hot.accept(__REDUCER_INDEX__, () => {
  store.replaceReducer(require(path.resolve(__REDUCER_INDEX__)));
});
```

But this provides the following error in the browser:

```
Uncaught SyntaxError: Invalid flags supplied to RegExp constructor 'd4'
```

I tried it with hard coded paths that make assumptions to the project directory, since `universal-redux` is meant to be in `node_modules` of the project:

```
module.hot.accept('./src/redux/modules/index', () => {
  store.replaceReducer(require(path.resolve(__dirname, '../../../../src/redux/modules/index')));
});
```

But this gives the an error when starting up:

```
[0] Critical dependencies:
[0] 47:27-67 the request of a dependency is an expression
[0]  @ ./~/universal-redux/lib/redux/create.js 47:27-67
```

...and does not reload reducers. I believe this is because the require statement is running from a different root than it used to.

Interestingly, the same error occurs even if I make a reducer inside of `universal-redux` that lives relative to the create.js just like the previous project. It's as if the base path of the hot reloading server does not know where to base its search.

**Comment by bdefore** [comment]
@gaearon perhaps you can see what i'm doing wrong here?

**Comment by gaearon** [comment]
Just to clarify.. Webpack analyzes `module.hot.accept()` calls at compile time. Both `require()` and `module.hot.accept()` need to have paths hard-coded there for hot reloading to work (as far as I know). I don't think it works with dynamic paths, no matter what you use to calculate them. Did it work before with dynamic paths for you?

**Comment by bdefore** [comment]
@gaearon i don't think it ever worked with dynamic paths, no. the original didn't need to because all of its reducers lived in a `./modules/index` path relative to where the store was created. my situation is somewhat different because i'm configuring webpack to build a bundle from the project root (via `contextRoot` and some webpack aliases) that includes this library as a dependency and has access to both `./src` as well as `./node_modules/universal-redux/src`

I've noticed that if I put the following in my setup:

```
    module.hot.accept('redux/modules/index', function () {
      console.log('replacing reducer in project...');
      store.replaceReducer(require('redux/modules/index'));
    });

    module.hot.accept('./modules/index', function () {
      console.log('replacing reducer in universal-redux...');
      store.replaceReducer(require('./modules/index'));
    });
```

It will hot reload the `modules/test` reducer relative to universal-redux, but not the `redux/modules/index` reducer relative to the project root. The console output after changing both files is:

```
[HMR] connected
[HMR] bundle rebuilding
[HMR] bundle rebuilt in 458ms
[HMR] Checking for updates on the server...
replacing reducer in universal-redux...
[HMR] Updated modules:
[HMR]  - ./~/universal-redux/lib/redux/modules/index.js
[HMR] App is up to date.
[HMR] bundle rebuilding
[HMR] bundle rebuilt in 498ms
[HMR] Checking for updates on the server...
[HMR] The following modules couldn't be hot updated: (Full reload needed)
[HMR]  - ./src/redux/modules/index.js
```

It's as if the accept route is not being mapped correctly.

**Comment by bdefore** [comment]
This issue still remains, but I've noticed that it occurs in react-redux-universal-hot-example too, in the same circumstances. I'm not sure I fully understand when a change to a reducer module is 'reloadable', and need to put together some steps that are reproducible. For example, either in universal-redux or in react-redux-universal-hot-example, adding a new property to the `initialState` appears to fail hot reloading with reducers that have already been initialized.

**Comment by gaearon** [comment]
Please file an issue with DevTools with instructions to reproduce.

**Comment by bdefore** [comment]
The commit that fixed this is here: https://github.com/bdefore/universal-redux/commit/436d748d64c288533c99b5415ba7483d58398ba6

What is not clear to me is why the import of reducers from a webpack alias, even if not used, would itself break hot reloading. All the way from initial client entry to the point where module.hot.accept is assigned, modules are required to be loaded via relative paths, or else modules fail to hot reload.
