### ISSUE TITLE
Where should GA code put on

### ISSUE THREAD

**Issue by sexyoung** [bdefore/redux-universal-renderer#75]
**Yes, it's me**

if I want to put **google analytics script**,
where should I put on?

if no use universal-redux, I always put it on `</body>` before
Thanks!

**Comment by bdefore** [comment]
@sexyoung Personally I've used this library https://github.com/seeden/react-g-analytics and just included it inside of my App.js (you could conceivably put it into a custom HTML shell if you prefer). Since the analytics library loads asynchronously anyway, I don't think there's any impact where you position it in your HTML.

**Comment by sexyoung** [comment]
oh ya, it's work!
**awsome**

**Comment by sexyoung** [comment]
by the way, if my App.js looks like this:

``` jsx
import React, { Component } from 'react';
import GoogleAnalytics from 'react-g-analytics';

export default class App extends Component {
  render() {
    return (
      <div className="page-container">
        {this.props.children}
        <GoogleAnalytics id="UA-XXXXXXXX-X" />
      </div>
    );
  }
}
```

if the GA id is different on develop and production,
I should be setting it somewhere?
is any config file?

**Comment by sexyoung** [comment]
I modify App.js like this:

``` jsx
import React, { Component } from 'react';
import GoogleAnalytics from 'react-g-analytics';

export default class App extends Component {

  constructor(){
    super();
    this.state = {
      GAID: (process.env.NODE_ENV === 'production'?"XXX":"YYY")
    }
  }

  render() {
    return (
      <div className="page-container">
        {this.props.children}
        <GoogleAnalytics id={this.state.GAID} />
      </div>
    );
  }
}
```

but I feel some strange, and I don't know how to do. :eyes:

**Comment by bdefore** [comment]
You can use the `globals` feature of universal-redux for example to set a `__GOOGLE_ANALYTICS_ID__: process.env.GOOGLE_ANALYTICS_ID` and then rely on a library like say https://github.com/motdotla/dotenv to bring those environment variables in via an `.env` file. You'll probably want to add `.env` to your `.gitignore` as well so that these don't end up in version control.

**Comment by sexyoung** [comment]
thank you! I'll setting it later.
I have a another question.
I want to my reducer fill default values.
so I create a new file on `/src/redux/reducers/todo.js`
and it's look like:

``` js
const initialState = [
  {
    id: 0,
    text: "default value",
  }
]

export default function todos(state = initialState, action){
  switch(action.type){
    case actionTypes.ADD_WORK:
      return [
          ...state,
          {
            id: action.id,
            text: action.text,
          }
        ];

    default:
      return state;
  }
}
```

and I can see `todos` in devTool panel. (reduxAsyncConnect and routing too)
but I don't know how to access `todos` from my components?
I define a routes.js like this:

``` jsx
import React from 'react';
import {Route, IndexRoute} from 'react-router';
import App from './containers/App/App';
import Home from "./pages/HomePage";
import About from "./pages/AboutPage";

export default () => {
  return (
    <Route path="/" component={App}>
      <IndexRoute component={Home} />
      <Route path="about" component={About} />
    </Route>
  );
};
```

but I don't know how to access `todos` from `HomePage.js`
Thank you for your answer!

**Comment by bdefore** [comment]
@sexyoung I think what you want is to use `connect` from Redux to link your action to your `HomePage` component. See the redux docs here for more information: http://redux.js.org/docs/basics/ExampleTodoList.html

This issue has gotten old and covers a few things. I'll close it but please re-open if you find anything defective with UR.

**Comment by sexyoung** [comment]
OK, thanks!
