### ISSUE TITLE
Question about ‘Add routes, reducer and rootClientComponent aliases so that client has access to them’

### ISSUE THREAD

**Issue by ferdinandsalis** [bdefore/redux-universal-renderer#80]
I am ignorant can you tell my why this is this case?

https://github.com/bdefore/universal-redux/blob/6fa6deaa0f0d99de52ac776472881655da014f7b/bin/merge-configs.js#L74-L79

Also thank you for this great project.

**Comment by bdefore** [comment]
thanks @ferdinandsalis ... these aliases exist so that we can do imports on the client, particularly in client.js here: https://github.com/bdefore/universal-redux/blob/master/src/client.js#L7-L10

**Comment by bdefore** [comment]
on the server, we can use the `path` library to resolve what people have configured, but on the client the only way I'm aware of is to use webpack aliases.

**Comment by ferdinandsalis** [comment]
@bdefore thanks for the clarification.

**Comment by sompylasar** [comment]
@bdefore Did you think of prefixing the injected aliases with your module name? The "routes" and "middleware" are quite common words, so there could be a userland module with such name, so this is not quite future-proof. Thanks.

**Comment by bdefore** [comment]
@sompylasar that's a good idea
