### ISSUE TITLE
Permissions issue with npm run dev on OSX

### ISSUE THREAD

**Issue by adailey14** [bdefore/redux-universal-renderer#9]
Just did a vanilla install of https://github.com/bdefore/react-redux-universal-hot-example/tree/example-project-simple-router on OSX. I ran into a permissions issue, and also maybe the cp command not working as expected based on the "usage" output below. Running 'npm run dev' with sudo gets farther but still outputs the "usage" message, and seems to hang at some point. Please let me know if I'm doing anything obviously wrong here.

I'm at node version 5.2.0, npm version 3.3.12.

```
git clone https://github.com/bdefore/react-redux-universal-hot-example/tree/example-project-simple-router
cd react-redux-universal-hot-example
npm install
(error about missing peers: history at 1.13.x and url-loader at x)
npm install url-loader (success)
npm install history@1.13.x (success)

npm run dev

cp bin/* $PROJECT_PATH/node_modules/redux-universal-starter/bin/; cp config/* $PROJECT_PATH/node_modules/redux-universal-starter/config/; babel src/ -w -d $PROJECT_PATH/node_modules/redux-universal-starter/lib

usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
Error: EACCES: permission denied, mkdir '/node_modules'
```

**Comment by bdefore** [comment]
@adailey14 i use `dev` while working on `universal-redux` in order to link differently than `npm link` for testing other projects. i think what you want is to run `npm run dev` in your project, not in `universal-redux` itself.

thanks for pointing this out i think i may need to rename the `dev` script as you're not the first to run into this. i may also need to update the README.

**Comment by bdefore** [comment]
@adailey14 based on those missing peer dependencies, are you using npm 2 by chance?

**Comment by adailey14** [comment]
@bdefore I am running npm run dev within this sample project (you link to it in universal-redux): https://github.com/bdefore/react-redux-universal-hot-example/tree/example-project-simple-router not within universal-redux. It didn't look like I could create an issue on the sample project, so I created it here.

And I'm at I'm at node version 5.2.0, npm version 3.3.12. I have seen those same missing peer dependencies (at least for `history@1.13.x`) on the erikras react-redux-universal-hot-loader project so I'd gotten used to ignoring them but it maybe something wrong with my setup.

**Comment by bdefore** [comment]
I tried to retrace your steps, but I'm failing where you're trying to clone directly to a branch:

```
git clone https://github.com/bdefore/react-redux-universal-hot-example/tree/example-project-simple-router
Cloning into 'example-project-simple-router'...
fatal: repository 'https://github.com/bdefore/react-redux-universal-hot-example/tree/example-project-simple-router/' not found
```

I think you mean to `git clone https://github.com/bdefore/react-redux-universal-hot-example` and then `git checkout example-project-simple-router`? Perhaps this might explain the `npm run dev` issue?

**Comment by adailey14** [comment]
@bdefore Oh I'm sorry I confused myself and pasted the wrong link (too many tabs open), I had cloned this project: https://github.com/bdefore/react-redux-universal-hot-example, not the simple-router version.

**Comment by bdefore** [comment]
I see, and you checkout the `example-project` branch after cloning? If I do that from scratch things seem to work fine. Here's my output: https://gist.github.com/bdefore/b6dab2c3255cb589fe4c

**Comment by adailey14** [comment]
Yeah sorry I ended up with a few too many repo / branch links and didn't understand how they fit together - maybe some others might share my confusion. This is now my understanding:

https://github.com/bdefore/universal-redux (This is your library for making universal redux apps)
https://github.com/bdefore/react-redux-universal-hot-example (This is your fork of erikras's project and a collection point for sample projects - I had checked this out (the master branch) thinking it was the refactored version using universal-redux, but really something else is happening on the master branch)
https://github.com/bdefore/react-redux-universal-hot-example/tree/example-project (Aha this is actually the example project I wanted)
https://github.com/bdefore/react-redux-universal-hot-example/tree/example-project-simple-router (And this is the example project but using simple-router)

I am going to check out the example project now, will let you know if I run into any issues!

**Comment by bdefore** [comment]
@adailey14 I think you've got it now. My fork's master branch is probably a stale version of the original and shouldn't be used. I'm using `example-project` as a branch for submitting one PR to the original repo, and `example-project-simple-router` for another.

**Comment by adailey14** [comment]
Ok thanks, I've got the proper example checked out now and everything is working well.

FYI I received this warning on npm install:
npm WARN EPEERINVALID karma-mocha@0.2.1 requires a peer of mocha@\* but none was installed.

I'm still a little unclear on what the expectation is regarding peer dependencies - but perhaps mocha should be added as an explicit dependency in the example project. I will close this issue now thank you so much for your help.

**Comment by bdefore** [comment]
You're welcome. And you're right on the mocha peer dependency. In fact I'd added it to `example-project-simple-router` but forgot to add it to the other. I've just pushed the addition.
