### ISSUE TITLE
@@router/UPDATE_LOCATION fired after first dispatched action

### ISSUE THREAD

**Issue by jazzido** [bdefore/redux-universal-renderer#91]
I've noticed that `@@router/UPDATE_LOCATION` (from react-redux-router) is being fired after the first action that is dispatched, immedialy after the initial page load:

![update-location-bug](https://cloud.githubusercontent.com/assets/27584/13512845/3b1ddc50-e16b-11e5-92e3-1635a5bf8aba.gif)

In my project, this is causing `redux-async-connect` to refetch the data that is already stored in the `state`.

[This branch of `universal-redux-starter`](https://github.com/jazzido/universal-redux-starter/tree/update-location-bug) reproduces the reported issue.

**Comment by bdefore** [comment]
Possibly relevant: https://github.com/erikras/react-redux-universal-hot-example/pull/961

**Comment by jazzido** [comment]
The issue is also present when `__DEVTOOLS__ == false`. Happens in production mode too: although the action logging is disabled, I notice the full page redraw.

Maybe it has to do with the synchronization of history that happens in `shared/create.js` ?

**Comment by jazzido** [comment]
I've partially addressed this in jazzido/universal-redux@ccba65b717634ef02c4db0df3682159ef8e7cc31. The most relevant changes are:
- [Initialization of memoryHistory with the current URL](https://github.com/jazzido/universal-redux/commit/ccba65b717634ef02c4db0df3682159ef8e7cc31#diff-83364b5d81f20e2bcb4f325396af4137R32)
- [Adding a `history` argument to the store creation function](https://github.com/jazzido/universal-redux/commit/ccba65b717634ef02c4db0df3682159ef8e7cc31#diff-e2e1576d60c340380c9d2488921f820aR22). Previously, it was created both from `server/providers/react-router` and `shared/create.js`

However, it seems that if DevComponent enabled, the full reload happens anyway. Since I don't use it in my project, I'm not affected by that issue. In any case, feel free to merge from my fork.

Thanks!
